services:
  wikijs:
    image: lscr.io/linuxserver/wikijs:latest
    container_name: wikijs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=wikijs
      - DB_USER=wikijs
      - DB_PASS=${POSTGRES_PASSWORD}
    volumes:
      - /mnt/data/wikijs/config:/config
      - /mnt/data/wikijs/data:/data
    ports:
      - 3000:3000
    restart: unless-stopped
    links:
      - db
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: wikijs
    volumes:
      - /mnt/data/postgres:/var/lib/postgresql/data
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/data/nginx.conf:/etc/nginx/nginx.conf
    links:
      - wikijs
